on:
  push:
    tags:
      - "v*"
  pull_request:
  workflow_dispatch:

jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main

  release:
    if: startsWith(github.ref, 'refs/tags/v')
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download firmware artifact
        uses: actions/download-artifact@v4
        with:
          name: firmware

      - name: Prepare firmware zip
        run: |
          echo "Looking for firmware.zip in workspace..."
          # show a short listing to help debugging
          echo "Workspace root: $(pwd)"
          find . -maxdepth 6 -type f -name 'firmware.zip' -print
          SRC=$(find . -maxdepth 6 -type f -name 'firmware.zip' | head -n1)
          if [ -z "$SRC" ]; then
            echo "ERROR: firmware.zip not found after downloading artifacts."
            echo "Workspace listing (top-level):"
            ls -la || true
            echo "Full find output (maxdepth 6):"
            find . -maxdepth 6 -print || true
            exit 1
          fi
          echo "Found firmware at: $SRC"
          cp "$SRC" ./firmware.zip
          echo "Copied to ./firmware.zip"
          ls -la firmware.zip

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false

      - name: Upload firmware asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./firmware.zip
          asset_name: firmware.zip
          asset_content_type: application/zip
