name: Release Firmware

on:
  push:
    tags:
      - "*" # Triggers on any tag push

jobs:
  download-artifact:
    if: ${{ github.event_name == 'workflow_dispatch' || (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success') }}
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact from build workflow
        uses: dawidd6/action-download-artifact@v3
        with:
          workflow: build.yml
          workflow_conclusion: success
          name: firmware
          path: ./firmware
          branch: master
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload downloaded firmware artifact
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: ./firmware

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.sha }}
          name: "Firmware Release ${{ github.sha }}"
          body: |
            Automated firmware release for commit ${{ github.sha }}.
            - Branch: ${{ github.ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload firmware to release
        uses: softprops/action-gh-release@v2
        with:
          files: ./firmware/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
