name: Download Firmware Artifact

on:
  workflow_dispatch:

jobs:
  download-artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact from build workflow
        uses: dawidd6/action-download-artifact@v3
        with:
          workflow: build.yml
          workflow_conclusion: success
          name: firmware
          path: ./firmware
          branch: master
          github_token: ${{ secrets.GITHUB_TOKEN }}
